//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class PendingGoodsIssueConsumer
    {
        public int ConsumerID { get; set; }
        public string ConsumerCode { get; set; }
        public string ConsumerName { get; set; }
        public string ConsumerVATCode { get; set; }
        public string ConsumerAttentionName { get; set; }
        public string ConsumerTelephone { get; set; }
        public string ConsumerAddressNo { get; set; }
        public string ConsumerEntireTerritoryEntireName { get; set; }
    }
}
